<?xml version="1.0" encoding="utf-8"?><Database Name="EasyBB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-88QDHD81\SQLSERVER2008;Initial Catalog=EasyBB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EasyBBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Action" Member="Action">
    <Type Name="Action">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="controller" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="action" Member="action1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ismenu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="enable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="addtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admin">
    <Type Name="Admin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pwd" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="addtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="avater" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="lastlogintime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="registerip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastloginip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="registercity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permission" Member="Permission">
    <Type Name="Permission">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="adminid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="actionid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="enable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="addtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Board" Member="Board">
    <Type Name="Board">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="intro" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="lastthemeid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lastlthemetime" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="lastuserid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lastthemetime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="themescount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="postcount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="avatar" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Posts" Member="Posts">
    <Type Name="Posts">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="[level]" Member="level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="borderid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="addtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ups" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="downs" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="collectcount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="themeid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Thems" Member="Thems">
    <Type Name="Thems">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="lastlevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="borderid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="addtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ups" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="downs" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="collectcount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pwd" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="addtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="lastlogintime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="registerip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastloginip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="signal" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="niname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="avatar" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="themecount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="postcount" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="logintime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="logincount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="points" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="userlever" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>