#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EasyBB")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertAction(Action instance);
    partial void UpdateAction(Action instance);
    partial void DeleteAction(Action instance);
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertPermission(Permission instance);
    partial void UpdatePermission(Permission instance);
    partial void DeletePermission(Permission instance);
    partial void InsertBoard(Board instance);
    partial void UpdateBoard(Board instance);
    partial void DeleteBoard(Board instance);
    partial void InsertThems(Thems instance);
    partial void UpdateThems(Thems instance);
    partial void DeleteThems(Thems instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EasyBBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Action> Action
		{
			get
			{
				return this.GetTable<Action>();
			}
		}
		
		public System.Data.Linq.Table<Admin> Admin
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<Permission> Permission
		{
			get
			{
				return this.GetTable<Permission>();
			}
		}
		
		public System.Data.Linq.Table<Board> Board
		{
			get
			{
				return this.GetTable<Board>();
			}
		}
		
		public System.Data.Linq.Table<Posts> Posts
		{
			get
			{
				return this.GetTable<Posts>();
			}
		}
		
		public System.Data.Linq.Table<Thems> Thems
		{
			get
			{
				return this.GetTable<Thems>();
			}
		}
		
		public System.Data.Linq.Table<User> User
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Action")]
	public partial class Action : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _controller;
		
		private string _action1;
		
		private int _pid;
		
		private bool _ismenu;
		
		private bool _enable;
		
		private System.DateTime _addtime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncontrollerChanging(string value);
    partial void OncontrollerChanged();
    partial void Onaction1Changing(string value);
    partial void Onaction1Changed();
    partial void OnpidChanging(int value);
    partial void OnpidChanged();
    partial void OnismenuChanging(bool value);
    partial void OnismenuChanged();
    partial void OnenableChanging(bool value);
    partial void OnenableChanged();
    partial void OnaddtimeChanging(System.DateTime value);
    partial void OnaddtimeChanged();
    #endregion
		
		public Action()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_controller", DbType="NVarChar(50)")]
		public string controller
		{
			get
			{
				return this._controller;
			}
			set
			{
				if ((this._controller != value))
				{
					this.OncontrollerChanging(value);
					this.SendPropertyChanging();
					this._controller = value;
					this.SendPropertyChanged("controller");
					this.OncontrollerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="action", Storage="_action1", DbType="NVarChar(50)")]
		public string action1
		{
			get
			{
				return this._action1;
			}
			set
			{
				if ((this._action1 != value))
				{
					this.Onaction1Changing(value);
					this.SendPropertyChanging();
					this._action1 = value;
					this.SendPropertyChanged("action1");
					this.Onaction1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="Int NOT NULL")]
		public int pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ismenu", DbType="Bit NOT NULL")]
		public bool ismenu
		{
			get
			{
				return this._ismenu;
			}
			set
			{
				if ((this._ismenu != value))
				{
					this.OnismenuChanging(value);
					this.SendPropertyChanging();
					this._ismenu = value;
					this.SendPropertyChanged("ismenu");
					this.OnismenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enable", DbType="Bit NOT NULL")]
		public bool enable
		{
			get
			{
				return this._enable;
			}
			set
			{
				if ((this._enable != value))
				{
					this.OnenableChanging(value);
					this.SendPropertyChanging();
					this._enable = value;
					this.SendPropertyChanged("enable");
					this.OnenableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addtime", DbType="DateTime NOT NULL")]
		public System.DateTime addtime
		{
			get
			{
				return this._addtime;
			}
			set
			{
				if ((this._addtime != value))
				{
					this.OnaddtimeChanging(value);
					this.SendPropertyChanging();
					this._addtime = value;
					this.SendPropertyChanged("addtime");
					this.OnaddtimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _pwd;
		
		private System.DateTime _addtime;
		
		private string _avater;
		
		private System.DateTime _lastlogintime;
		
		private string _registerip;
		
		private string _lastloginip;
		
		private int _status;
		
		private string _registercity;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void OnaddtimeChanging(System.DateTime value);
    partial void OnaddtimeChanged();
    partial void OnavaterChanging(string value);
    partial void OnavaterChanged();
    partial void OnlastlogintimeChanging(System.DateTime value);
    partial void OnlastlogintimeChanged();
    partial void OnregisteripChanging(string value);
    partial void OnregisteripChanged();
    partial void OnlastloginipChanging(string value);
    partial void OnlastloginipChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    partial void OnregistercityChanging(string value);
    partial void OnregistercityChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this.OnpwdChanging(value);
					this.SendPropertyChanging();
					this._pwd = value;
					this.SendPropertyChanged("pwd");
					this.OnpwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addtime", DbType="DateTime NOT NULL")]
		public System.DateTime addtime
		{
			get
			{
				return this._addtime;
			}
			set
			{
				if ((this._addtime != value))
				{
					this.OnaddtimeChanging(value);
					this.SendPropertyChanging();
					this._addtime = value;
					this.SendPropertyChanged("addtime");
					this.OnaddtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avater", DbType="NVarChar(250)")]
		public string avater
		{
			get
			{
				return this._avater;
			}
			set
			{
				if ((this._avater != value))
				{
					this.OnavaterChanging(value);
					this.SendPropertyChanging();
					this._avater = value;
					this.SendPropertyChanged("avater");
					this.OnavaterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastlogintime", DbType="DateTime NOT NULL")]
		public System.DateTime lastlogintime
		{
			get
			{
				return this._lastlogintime;
			}
			set
			{
				if ((this._lastlogintime != value))
				{
					this.OnlastlogintimeChanging(value);
					this.SendPropertyChanging();
					this._lastlogintime = value;
					this.SendPropertyChanged("lastlogintime");
					this.OnlastlogintimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registerip", DbType="NVarChar(50)")]
		public string registerip
		{
			get
			{
				return this._registerip;
			}
			set
			{
				if ((this._registerip != value))
				{
					this.OnregisteripChanging(value);
					this.SendPropertyChanging();
					this._registerip = value;
					this.SendPropertyChanged("registerip");
					this.OnregisteripChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastloginip", DbType="NVarChar(50)")]
		public string lastloginip
		{
			get
			{
				return this._lastloginip;
			}
			set
			{
				if ((this._lastloginip != value))
				{
					this.OnlastloginipChanging(value);
					this.SendPropertyChanging();
					this._lastloginip = value;
					this.SendPropertyChanged("lastloginip");
					this.OnlastloginipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registercity", DbType="NVarChar(50)")]
		public string registercity
		{
			get
			{
				return this._registercity;
			}
			set
			{
				if ((this._registercity != value))
				{
					this.OnregistercityChanging(value);
					this.SendPropertyChanging();
					this._registercity = value;
					this.SendPropertyChanged("registercity");
					this.OnregistercityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Permission")]
	public partial class Permission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _adminid;
		
		private System.Nullable<int> _actionid;
		
		private System.Nullable<bool> _enable;
		
		private System.Nullable<System.DateTime> _addtime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadminidChanging(System.Nullable<int> value);
    partial void OnadminidChanged();
    partial void OnactionidChanging(System.Nullable<int> value);
    partial void OnactionidChanged();
    partial void OnenableChanging(System.Nullable<bool> value);
    partial void OnenableChanged();
    partial void OnaddtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnaddtimeChanged();
    #endregion
		
		public Permission()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminid", DbType="Int")]
		public System.Nullable<int> adminid
		{
			get
			{
				return this._adminid;
			}
			set
			{
				if ((this._adminid != value))
				{
					this.OnadminidChanging(value);
					this.SendPropertyChanging();
					this._adminid = value;
					this.SendPropertyChanged("adminid");
					this.OnadminidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actionid", DbType="Int")]
		public System.Nullable<int> actionid
		{
			get
			{
				return this._actionid;
			}
			set
			{
				if ((this._actionid != value))
				{
					this.OnactionidChanging(value);
					this.SendPropertyChanging();
					this._actionid = value;
					this.SendPropertyChanged("actionid");
					this.OnactionidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enable", DbType="Bit")]
		public System.Nullable<bool> enable
		{
			get
			{
				return this._enable;
			}
			set
			{
				if ((this._enable != value))
				{
					this.OnenableChanging(value);
					this.SendPropertyChanging();
					this._enable = value;
					this.SendPropertyChanged("enable");
					this.OnenableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> addtime
		{
			get
			{
				return this._addtime;
			}
			set
			{
				if ((this._addtime != value))
				{
					this.OnaddtimeChanging(value);
					this.SendPropertyChanging();
					this._addtime = value;
					this.SendPropertyChanged("addtime");
					this.OnaddtimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Board")]
	public partial class Board : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _intro;
		
		private int _lastthemeid;
		
		private string _lastlthemetime;
		
		private int _lastuserid;
		
		private int _lastthemetime;
		
		private int _status;
		
		private long _themescount;
		
		private long _postcount;
		
		private string _avatar;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnintroChanging(string value);
    partial void OnintroChanged();
    partial void OnlastthemeidChanging(int value);
    partial void OnlastthemeidChanged();
    partial void OnlastlthemetimeChanging(string value);
    partial void OnlastlthemetimeChanged();
    partial void OnlastuseridChanging(int value);
    partial void OnlastuseridChanged();
    partial void OnlastthemetimeChanging(int value);
    partial void OnlastthemetimeChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    partial void OnthemescountChanging(long value);
    partial void OnthemescountChanged();
    partial void OnpostcountChanging(long value);
    partial void OnpostcountChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    #endregion
		
		public Board()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intro", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
		public string intro
		{
			get
			{
				return this._intro;
			}
			set
			{
				if ((this._intro != value))
				{
					this.OnintroChanging(value);
					this.SendPropertyChanging();
					this._intro = value;
					this.SendPropertyChanged("intro");
					this.OnintroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastthemeid", DbType="Int NOT NULL")]
		public int lastthemeid
		{
			get
			{
				return this._lastthemeid;
			}
			set
			{
				if ((this._lastthemeid != value))
				{
					this.OnlastthemeidChanging(value);
					this.SendPropertyChanging();
					this._lastthemeid = value;
					this.SendPropertyChanged("lastthemeid");
					this.OnlastthemeidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastlthemetime", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string lastlthemetime
		{
			get
			{
				return this._lastlthemetime;
			}
			set
			{
				if ((this._lastlthemetime != value))
				{
					this.OnlastlthemetimeChanging(value);
					this.SendPropertyChanging();
					this._lastlthemetime = value;
					this.SendPropertyChanged("lastlthemetime");
					this.OnlastlthemetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastuserid", DbType="Int NOT NULL")]
		public int lastuserid
		{
			get
			{
				return this._lastuserid;
			}
			set
			{
				if ((this._lastuserid != value))
				{
					this.OnlastuseridChanging(value);
					this.SendPropertyChanging();
					this._lastuserid = value;
					this.SendPropertyChanged("lastuserid");
					this.OnlastuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastthemetime", DbType="Int NOT NULL")]
		public int lastthemetime
		{
			get
			{
				return this._lastthemetime;
			}
			set
			{
				if ((this._lastthemetime != value))
				{
					this.OnlastthemetimeChanging(value);
					this.SendPropertyChanging();
					this._lastthemetime = value;
					this.SendPropertyChanged("lastthemetime");
					this.OnlastthemetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_themescount", DbType="BigInt NOT NULL")]
		public long themescount
		{
			get
			{
				return this._themescount;
			}
			set
			{
				if ((this._themescount != value))
				{
					this.OnthemescountChanging(value);
					this.SendPropertyChanging();
					this._themescount = value;
					this.SendPropertyChanged("themescount");
					this.OnthemescountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postcount", DbType="BigInt NOT NULL")]
		public long postcount
		{
			get
			{
				return this._postcount;
			}
			set
			{
				if ((this._postcount != value))
				{
					this.OnpostcountChanging(value);
					this.SendPropertyChanging();
					this._postcount = value;
					this.SendPropertyChanged("postcount");
					this.OnpostcountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Posts")]
	public partial class Posts
	{
		
		private int _id;
		
		private string _content;
		
		private int _level;
		
		private int _userid;
		
		private int _borderid;
		
		private System.DateTime _addtime;
		
		private int _status;
		
		private long _ups;
		
		private long _downs;
		
		private long _collectcount;
		
		private int _themeid;
		
		public Posts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this._content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="Int NOT NULL")]
		public int level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this._level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borderid", DbType="Int NOT NULL")]
		public int borderid
		{
			get
			{
				return this._borderid;
			}
			set
			{
				if ((this._borderid != value))
				{
					this._borderid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addtime", DbType="DateTime NOT NULL")]
		public System.DateTime addtime
		{
			get
			{
				return this._addtime;
			}
			set
			{
				if ((this._addtime != value))
				{
					this._addtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ups", DbType="BigInt NOT NULL")]
		public long ups
		{
			get
			{
				return this._ups;
			}
			set
			{
				if ((this._ups != value))
				{
					this._ups = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downs", DbType="BigInt NOT NULL")]
		public long downs
		{
			get
			{
				return this._downs;
			}
			set
			{
				if ((this._downs != value))
				{
					this._downs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collectcount", DbType="BigInt NOT NULL")]
		public long collectcount
		{
			get
			{
				return this._collectcount;
			}
			set
			{
				if ((this._collectcount != value))
				{
					this._collectcount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_themeid", DbType="Int NOT NULL")]
		public int themeid
		{
			get
			{
				return this._themeid;
			}
			set
			{
				if ((this._themeid != value))
				{
					this._themeid = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thems")]
	public partial class Thems : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
		private string _content;
		
		private int _lastlevel;
		
		private int _userid;
		
		private int _borderid;
		
		private System.DateTime _addtime;
		
		private int _status;
		
		private long _ups;
		
		private long _downs;
		
		private long _collectcount;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OnlastlevelChanging(int value);
    partial void OnlastlevelChanged();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OnborderidChanging(int value);
    partial void OnborderidChanged();
    partial void OnaddtimeChanging(System.DateTime value);
    partial void OnaddtimeChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    partial void OnupsChanging(long value);
    partial void OnupsChanged();
    partial void OndownsChanging(long value);
    partial void OndownsChanged();
    partial void OncollectcountChanging(long value);
    partial void OncollectcountChanged();
    #endregion
		
		public Thems()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastlevel", DbType="Int NOT NULL")]
		public int lastlevel
		{
			get
			{
				return this._lastlevel;
			}
			set
			{
				if ((this._lastlevel != value))
				{
					this.OnlastlevelChanging(value);
					this.SendPropertyChanging();
					this._lastlevel = value;
					this.SendPropertyChanged("lastlevel");
					this.OnlastlevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borderid", DbType="Int NOT NULL")]
		public int borderid
		{
			get
			{
				return this._borderid;
			}
			set
			{
				if ((this._borderid != value))
				{
					this.OnborderidChanging(value);
					this.SendPropertyChanging();
					this._borderid = value;
					this.SendPropertyChanged("borderid");
					this.OnborderidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addtime", DbType="DateTime NOT NULL")]
		public System.DateTime addtime
		{
			get
			{
				return this._addtime;
			}
			set
			{
				if ((this._addtime != value))
				{
					this.OnaddtimeChanging(value);
					this.SendPropertyChanging();
					this._addtime = value;
					this.SendPropertyChanged("addtime");
					this.OnaddtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ups", DbType="BigInt NOT NULL")]
		public long ups
		{
			get
			{
				return this._ups;
			}
			set
			{
				if ((this._ups != value))
				{
					this.OnupsChanging(value);
					this.SendPropertyChanging();
					this._ups = value;
					this.SendPropertyChanged("ups");
					this.OnupsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downs", DbType="BigInt NOT NULL")]
		public long downs
		{
			get
			{
				return this._downs;
			}
			set
			{
				if ((this._downs != value))
				{
					this.OndownsChanging(value);
					this.SendPropertyChanging();
					this._downs = value;
					this.SendPropertyChanged("downs");
					this.OndownsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collectcount", DbType="BigInt NOT NULL")]
		public long collectcount
		{
			get
			{
				return this._collectcount;
			}
			set
			{
				if ((this._collectcount != value))
				{
					this.OncollectcountChanging(value);
					this.SendPropertyChanging();
					this._collectcount = value;
					this.SendPropertyChanged("collectcount");
					this.OncollectcountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _pwd;
		
		private System.DateTime _addtime;
		
		private System.DateTime _lastlogintime;
		
		private string _registerip;
		
		private string _lastloginip;
		
		private int _status;
		
		private string _signal;
		
		private string _niname;
		
		private string _avatar;
		
		private long _themecount;
		
		private string _postcount;
		
		private long _logintime;
		
		private long _logincount;
		
		private long _points;
		
		private int _userlever;
		
		private string _email;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void OnaddtimeChanging(System.DateTime value);
    partial void OnaddtimeChanged();
    partial void OnlastlogintimeChanging(System.DateTime value);
    partial void OnlastlogintimeChanged();
    partial void OnregisteripChanging(string value);
    partial void OnregisteripChanged();
    partial void OnlastloginipChanging(string value);
    partial void OnlastloginipChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    partial void OnsignalChanging(string value);
    partial void OnsignalChanged();
    partial void OnninameChanging(string value);
    partial void OnninameChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    partial void OnthemecountChanging(long value);
    partial void OnthemecountChanged();
    partial void OnpostcountChanging(string value);
    partial void OnpostcountChanged();
    partial void OnlogintimeChanging(long value);
    partial void OnlogintimeChanged();
    partial void OnlogincountChanging(long value);
    partial void OnlogincountChanged();
    partial void OnpointsChanging(long value);
    partial void OnpointsChanged();
    partial void OnuserleverChanging(int value);
    partial void OnuserleverChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this.OnpwdChanging(value);
					this.SendPropertyChanging();
					this._pwd = value;
					this.SendPropertyChanged("pwd");
					this.OnpwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addtime", DbType="DateTime NOT NULL")]
		public System.DateTime addtime
		{
			get
			{
				return this._addtime;
			}
			set
			{
				if ((this._addtime != value))
				{
					this.OnaddtimeChanging(value);
					this.SendPropertyChanging();
					this._addtime = value;
					this.SendPropertyChanged("addtime");
					this.OnaddtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastlogintime", DbType="DateTime NOT NULL")]
		public System.DateTime lastlogintime
		{
			get
			{
				return this._lastlogintime;
			}
			set
			{
				if ((this._lastlogintime != value))
				{
					this.OnlastlogintimeChanging(value);
					this.SendPropertyChanging();
					this._lastlogintime = value;
					this.SendPropertyChanged("lastlogintime");
					this.OnlastlogintimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registerip", DbType="NVarChar(50)")]
		public string registerip
		{
			get
			{
				return this._registerip;
			}
			set
			{
				if ((this._registerip != value))
				{
					this.OnregisteripChanging(value);
					this.SendPropertyChanging();
					this._registerip = value;
					this.SendPropertyChanged("registerip");
					this.OnregisteripChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastloginip", DbType="NVarChar(50)")]
		public string lastloginip
		{
			get
			{
				return this._lastloginip;
			}
			set
			{
				if ((this._lastloginip != value))
				{
					this.OnlastloginipChanging(value);
					this.SendPropertyChanging();
					this._lastloginip = value;
					this.SendPropertyChanged("lastloginip");
					this.OnlastloginipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signal", DbType="NVarChar(250)")]
		public string signal
		{
			get
			{
				return this._signal;
			}
			set
			{
				if ((this._signal != value))
				{
					this.OnsignalChanging(value);
					this.SendPropertyChanging();
					this._signal = value;
					this.SendPropertyChanged("signal");
					this.OnsignalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string niname
		{
			get
			{
				return this._niname;
			}
			set
			{
				if ((this._niname != value))
				{
					this.OnninameChanging(value);
					this.SendPropertyChanging();
					this._niname = value;
					this.SendPropertyChanged("niname");
					this.OnninameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_themecount", DbType="BigInt NOT NULL")]
		public long themecount
		{
			get
			{
				return this._themecount;
			}
			set
			{
				if ((this._themecount != value))
				{
					this.OnthemecountChanging(value);
					this.SendPropertyChanging();
					this._themecount = value;
					this.SendPropertyChanged("themecount");
					this.OnthemecountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postcount", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string postcount
		{
			get
			{
				return this._postcount;
			}
			set
			{
				if ((this._postcount != value))
				{
					this.OnpostcountChanging(value);
					this.SendPropertyChanging();
					this._postcount = value;
					this.SendPropertyChanged("postcount");
					this.OnpostcountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logintime", DbType="BigInt NOT NULL")]
		public long logintime
		{
			get
			{
				return this._logintime;
			}
			set
			{
				if ((this._logintime != value))
				{
					this.OnlogintimeChanging(value);
					this.SendPropertyChanging();
					this._logintime = value;
					this.SendPropertyChanged("logintime");
					this.OnlogintimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logincount", DbType="BigInt NOT NULL")]
		public long logincount
		{
			get
			{
				return this._logincount;
			}
			set
			{
				if ((this._logincount != value))
				{
					this.OnlogincountChanging(value);
					this.SendPropertyChanging();
					this._logincount = value;
					this.SendPropertyChanged("logincount");
					this.OnlogincountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_points", DbType="BigInt NOT NULL")]
		public long points
		{
			get
			{
				return this._points;
			}
			set
			{
				if ((this._points != value))
				{
					this.OnpointsChanging(value);
					this.SendPropertyChanging();
					this._points = value;
					this.SendPropertyChanged("points");
					this.OnpointsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userlever", DbType="Int NOT NULL")]
		public int userlever
		{
			get
			{
				return this._userlever;
			}
			set
			{
				if ((this._userlever != value))
				{
					this.OnuserleverChanging(value);
					this.SendPropertyChanging();
					this._userlever = value;
					this.SendPropertyChanged("userlever");
					this.OnuserleverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
